"""postgres identity and usage counter safety

Revision ID: 20260320_0005
Revises: 20260319_0004
Create Date: 2026-03-20 09:15:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260320_0005"
down_revision = "20260319_0004"
branch_labels = None
depends_on = None


def _ensure_postgres_identity(table_name: str) -> None:
    op.execute(
        sa.text(
            f"""
            DO $$
            DECLARE
                current_identity text;
                current_sequence text;
                max_id bigint;
            BEGIN
                SELECT is_identity
                INTO current_identity
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = '{table_name}'
                  AND column_name = 'id';

                EXECUTE format(
                    'ALTER TABLE %I.%I ALTER COLUMN %I SET NOT NULL',
                    current_schema(),
                    '{table_name}',
                    'id'
                );

                IF current_identity IS DISTINCT FROM 'YES' THEN
                    SELECT pg_get_serial_sequence(format('%I.%I', current_schema(), '{table_name}'), 'id')
                    INTO current_sequence;

                    BEGIN
                        EXECUTE format(
                            'ALTER TABLE %I.%I ALTER COLUMN %I DROP DEFAULT',
                            current_schema(),
                            '{table_name}',
                            'id'
                        );
                    EXCEPTION
                        WHEN undefined_object THEN
                            NULL;
                    END;

                    IF current_sequence IS NOT NULL THEN
                        EXECUTE 'DROP SEQUENCE IF EXISTS ' || current_sequence;
                    END IF;

                    EXECUTE format(
                        'ALTER TABLE %I.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                        current_schema(),
                        '{table_name}',
                        'id'
                    );
                END IF;

                SELECT pg_get_serial_sequence(format('%I.%I', current_schema(), '{table_name}'), 'id')
                INTO current_sequence;

                IF current_sequence IS NOT NULL THEN
                    EXECUTE format(
                        'SELECT COALESCE(MAX(%I), 0) FROM %I.%I',
                        'id',
                        current_schema(),
                        '{table_name}'
                    )
                    INTO max_id;

                    IF max_id > 0 THEN
                        EXECUTE format('SELECT setval(%L, %s, true)', current_sequence, max_id);
                    ELSE
                        EXECUTE format('SELECT setval(%L, 1, false)', current_sequence);
                    END IF;
                END IF;
            END $$;
            """
        )
    )


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return

    for table_name in ("users", "memberships", "usage_counters", "photos"):
        _ensure_postgres_identity(table_name)


def downgrade() -> None:
    raise NotImplementedError("Downgrades are disabled for production safety. Use forward Alembic upgrades only.")
